package asterai:math;

world plugin {
  use asterai:host/context@0.1.0.{plugin-context};

  export add: func(input: binary-operation-input) -> output;

  record binary-operation-input {
    context: plugin-context,
    a: f64,
    b: f64,
  }

  record output {
    system-message: string,
  }
}
