// TODO: source this from a central public repo.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: asterai.proto

package asterai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *AppQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *PluginContext) Reset() {
	*x = PluginContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginContext) ProtoMessage() {}

func (x *PluginContext) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginContext.ProtoReflect.Descriptor instead.
func (*PluginContext) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{0}
}

func (x *PluginContext) GetQuery() *AppQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type AppQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content             string  `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TimestampUnixMillis int64   `protobuf:"varint,2,opt,name=timestamp_unix_millis,json=timestampUnixMillis,proto3" json:"timestamp_unix_millis,omitempty"`
	UserId              *string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
}

func (x *AppQuery) Reset() {
	*x = AppQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppQuery) ProtoMessage() {}

func (x *AppQuery) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppQuery.ProtoReflect.Descriptor instead.
func (*AppQuery) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{1}
}

func (x *AppQuery) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AppQuery) GetTimestampUnixMillis() int64 {
	if x != nil {
		return x.TimestampUnixMillis
	}
	return 0
}

func (x *AppQuery) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type HostHashStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *HostHashStringRequest) Reset() {
	*x = HostHashStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostHashStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostHashStringRequest) ProtoMessage() {}

func (x *HostHashStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostHashStringRequest.ProtoReflect.Descriptor instead.
func (*HostHashStringRequest) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{2}
}

func (x *HostHashStringRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type HostHashStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *HostHashStringResponse) Reset() {
	*x = HostHashStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostHashStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostHashStringResponse) ProtoMessage() {}

func (x *HostHashStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostHashStringResponse.ProtoReflect.Descriptor instead.
func (*HostHashStringResponse) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{3}
}

func (x *HostHashStringResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type HostHmacHashStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Hash    string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Key     string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HostHmacHashStringRequest) Reset() {
	*x = HostHmacHashStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostHmacHashStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostHmacHashStringRequest) ProtoMessage() {}

func (x *HostHmacHashStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostHmacHashStringRequest.ProtoReflect.Descriptor instead.
func (*HostHmacHashStringRequest) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{4}
}

func (x *HostHmacHashStringRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HostHmacHashStringRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *HostHmacHashStringRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type HostVectorEmbeddingStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content           string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	AppCollectionName string `protobuf:"bytes,2,opt,name=app_collection_name,json=appCollectionName,proto3" json:"app_collection_name,omitempty"`
}

func (x *HostVectorEmbeddingStoreRequest) Reset() {
	*x = HostVectorEmbeddingStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostVectorEmbeddingStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostVectorEmbeddingStoreRequest) ProtoMessage() {}

func (x *HostVectorEmbeddingStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostVectorEmbeddingStoreRequest.ProtoReflect.Descriptor instead.
func (*HostVectorEmbeddingStoreRequest) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{5}
}

func (x *HostVectorEmbeddingStoreRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HostVectorEmbeddingStoreRequest) GetAppCollectionName() string {
	if x != nil {
		return x.AppCollectionName
	}
	return ""
}

type HostVectorEmbeddingSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query             string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	AppCollectionName string `protobuf:"bytes,2,opt,name=app_collection_name,json=appCollectionName,proto3" json:"app_collection_name,omitempty"`
}

func (x *HostVectorEmbeddingSearchRequest) Reset() {
	*x = HostVectorEmbeddingSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostVectorEmbeddingSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostVectorEmbeddingSearchRequest) ProtoMessage() {}

func (x *HostVectorEmbeddingSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostVectorEmbeddingSearchRequest.ProtoReflect.Descriptor instead.
func (*HostVectorEmbeddingSearchRequest) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{6}
}

func (x *HostVectorEmbeddingSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HostVectorEmbeddingSearchRequest) GetAppCollectionName() string {
	if x != nil {
		return x.AppCollectionName
	}
	return ""
}

type HostVectorEmbeddingSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*HostVectorEmbeddingSimilarityScore `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *HostVectorEmbeddingSearchResponse) Reset() {
	*x = HostVectorEmbeddingSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostVectorEmbeddingSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostVectorEmbeddingSearchResponse) ProtoMessage() {}

func (x *HostVectorEmbeddingSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostVectorEmbeddingSearchResponse.ProtoReflect.Descriptor instead.
func (*HostVectorEmbeddingSearchResponse) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{7}
}

func (x *HostVectorEmbeddingSearchResponse) GetResults() []*HostVectorEmbeddingSimilarityScore {
	if x != nil {
		return x.Results
	}
	return nil
}

type HostVectorEmbeddingSimilarityScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score   float32           `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	Payload map[string]string `protobuf:"bytes,2,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HostVectorEmbeddingSimilarityScore) Reset() {
	*x = HostVectorEmbeddingSimilarityScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostVectorEmbeddingSimilarityScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostVectorEmbeddingSimilarityScore) ProtoMessage() {}

func (x *HostVectorEmbeddingSimilarityScore) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostVectorEmbeddingSimilarityScore.ProtoReflect.Descriptor instead.
func (*HostVectorEmbeddingSimilarityScore) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{8}
}

func (x *HostVectorEmbeddingSimilarityScore) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *HostVectorEmbeddingSimilarityScore) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HostLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Level   string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *HostLogRequest) Reset() {
	*x = HostLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostLogRequest) ProtoMessage() {}

func (x *HostLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostLogRequest.ProtoReflect.Descriptor instead.
func (*HostLogRequest) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{9}
}

func (x *HostLogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HostLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type HostHttpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request string `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *HostHttpRequest) Reset() {
	*x = HostHttpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostHttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostHttpRequest) ProtoMessage() {}

func (x *HostHttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostHttpRequest.ProtoReflect.Descriptor instead.
func (*HostHttpRequest) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{10}
}

func (x *HostHttpRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type HostHttpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *HostHttpResponse) Reset() {
	*x = HostHttpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostHttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostHttpResponse) ProtoMessage() {}

func (x *HostHttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostHttpResponse.ProtoReflect.Descriptor instead.
func (*HostHttpResponse) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{11}
}

func (x *HostHttpResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type HostKvGetUserStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HostKvGetUserStringRequest) Reset() {
	*x = HostKvGetUserStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostKvGetUserStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostKvGetUserStringRequest) ProtoMessage() {}

func (x *HostKvGetUserStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostKvGetUserStringRequest.ProtoReflect.Descriptor instead.
func (*HostKvGetUserStringRequest) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{12}
}

func (x *HostKvGetUserStringRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HostKvGetUserStringRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type HostKvGetUserStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *string `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *HostKvGetUserStringResponse) Reset() {
	*x = HostKvGetUserStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostKvGetUserStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostKvGetUserStringResponse) ProtoMessage() {}

func (x *HostKvGetUserStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostKvGetUserStringResponse.ProtoReflect.Descriptor instead.
func (*HostKvGetUserStringResponse) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{13}
}

func (x *HostKvGetUserStringResponse) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type HostKvSetUserStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Key    string  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value  *string `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *HostKvSetUserStringRequest) Reset() {
	*x = HostKvSetUserStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostKvSetUserStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostKvSetUserStringRequest) ProtoMessage() {}

func (x *HostKvSetUserStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostKvSetUserStringRequest.ProtoReflect.Descriptor instead.
func (*HostKvSetUserStringRequest) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{14}
}

func (x *HostKvSetUserStringRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HostKvSetUserStringRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HostKvSetUserStringRequest) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type HostPluginEnvGetStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HostPluginEnvGetStringRequest) Reset() {
	*x = HostPluginEnvGetStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostPluginEnvGetStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostPluginEnvGetStringRequest) ProtoMessage() {}

func (x *HostPluginEnvGetStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostPluginEnvGetStringRequest.ProtoReflect.Descriptor instead.
func (*HostPluginEnvGetStringRequest) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{15}
}

func (x *HostPluginEnvGetStringRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type HostPluginEnvGetStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *string `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *HostPluginEnvGetStringResponse) Reset() {
	*x = HostPluginEnvGetStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asterai_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostPluginEnvGetStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostPluginEnvGetStringResponse) ProtoMessage() {}

func (x *HostPluginEnvGetStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asterai_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostPluginEnvGetStringResponse.ProtoReflect.Descriptor instead.
func (*HostPluginEnvGetStringResponse) Descriptor() ([]byte, []int) {
	return file_asterai_proto_rawDescGZIP(), []int{16}
}

func (x *HostPluginEnvGetStringResponse) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

var File_asterai_proto protoreflect.FileDescriptor

var file_asterai_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x30, 0x0a, 0x0d, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x1f, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x41, 0x70, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x15, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x12, 0x1c, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x48, 0x6f, 0x73, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x16, 0x48, 0x6f, 0x73,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x5b, 0x0a, 0x19, 0x48, 0x6f, 0x73, 0x74, 0x48,
	0x6d, 0x61, 0x63, 0x48, 0x61, 0x73, 0x68, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x6b, 0x0a, 0x1f, 0x48, 0x6f, 0x73, 0x74, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x2e, 0x0a, 0x13, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x61, 0x70, 0x70, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x68, 0x0a, 0x20, 0x48, 0x6f, 0x73, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x2e, 0x0a, 0x13, 0x61,
	0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x62, 0x0a, 0x21, 0x48,
	0x6f, 0x73, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74,
	0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22,
	0xc2, 0x01, 0x0a, 0x22, 0x48, 0x6f, 0x73, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74,
	0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x4a, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x3a, 0x0a, 0x0c, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x40, 0x0a, 0x0e, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x2b, 0x0a, 0x0f, 0x48, 0x6f, 0x73, 0x74, 0x48, 0x74,
	0x74, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x10, 0x48, 0x6f, 0x73, 0x74, 0x48, 0x74, 0x74, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x1a, 0x48, 0x6f, 0x73, 0x74, 0x4b, 0x76, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x42, 0x0a, 0x1b,
	0x48, 0x6f, 0x73, 0x74, 0x4b, 0x76, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x6c, 0x0a, 0x1a, 0x48, 0x6f, 0x73, 0x74, 0x4b, 0x76, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x31,
	0x0a, 0x1d, 0x48, 0x6f, 0x73, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x45, 0x6e, 0x76, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x45, 0x0a, 0x1e, 0x48, 0x6f, 0x73, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x45,
	0x6e, 0x76, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x61, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_asterai_proto_rawDescOnce sync.Once
	file_asterai_proto_rawDescData = file_asterai_proto_rawDesc
)

func file_asterai_proto_rawDescGZIP() []byte {
	file_asterai_proto_rawDescOnce.Do(func() {
		file_asterai_proto_rawDescData = protoimpl.X.CompressGZIP(file_asterai_proto_rawDescData)
	})
	return file_asterai_proto_rawDescData
}

var file_asterai_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_asterai_proto_goTypes = []interface{}{
	(*PluginContext)(nil),                      // 0: PluginContext
	(*AppQuery)(nil),                           // 1: AppQuery
	(*HostHashStringRequest)(nil),              // 2: HostHashStringRequest
	(*HostHashStringResponse)(nil),             // 3: HostHashStringResponse
	(*HostHmacHashStringRequest)(nil),          // 4: HostHmacHashStringRequest
	(*HostVectorEmbeddingStoreRequest)(nil),    // 5: HostVectorEmbeddingStoreRequest
	(*HostVectorEmbeddingSearchRequest)(nil),   // 6: HostVectorEmbeddingSearchRequest
	(*HostVectorEmbeddingSearchResponse)(nil),  // 7: HostVectorEmbeddingSearchResponse
	(*HostVectorEmbeddingSimilarityScore)(nil), // 8: HostVectorEmbeddingSimilarityScore
	(*HostLogRequest)(nil),                     // 9: HostLogRequest
	(*HostHttpRequest)(nil),                    // 10: HostHttpRequest
	(*HostHttpResponse)(nil),                   // 11: HostHttpResponse
	(*HostKvGetUserStringRequest)(nil),         // 12: HostKvGetUserStringRequest
	(*HostKvGetUserStringResponse)(nil),        // 13: HostKvGetUserStringResponse
	(*HostKvSetUserStringRequest)(nil),         // 14: HostKvSetUserStringRequest
	(*HostPluginEnvGetStringRequest)(nil),      // 15: HostPluginEnvGetStringRequest
	(*HostPluginEnvGetStringResponse)(nil),     // 16: HostPluginEnvGetStringResponse
	nil,                                        // 17: HostVectorEmbeddingSimilarityScore.PayloadEntry
}
var file_asterai_proto_depIdxs = []int32{
	1,  // 0: PluginContext.query:type_name -> AppQuery
	8,  // 1: HostVectorEmbeddingSearchResponse.results:type_name -> HostVectorEmbeddingSimilarityScore
	17, // 2: HostVectorEmbeddingSimilarityScore.payload:type_name -> HostVectorEmbeddingSimilarityScore.PayloadEntry
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_asterai_proto_init() }
func file_asterai_proto_init() {
	if File_asterai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_asterai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostHashStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostHashStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostHmacHashStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostVectorEmbeddingStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostVectorEmbeddingSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostVectorEmbeddingSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostVectorEmbeddingSimilarityScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostHttpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostHttpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostKvGetUserStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostKvGetUserStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostKvSetUserStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostPluginEnvGetStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asterai_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostPluginEnvGetStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_asterai_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_asterai_proto_msgTypes[13].OneofWrappers = []interface{}{}
	file_asterai_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_asterai_proto_msgTypes[16].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_asterai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_asterai_proto_goTypes,
		DependencyIndexes: file_asterai_proto_depIdxs,
		MessageInfos:      file_asterai_proto_msgTypes,
	}.Build()
	File_asterai_proto = out.File
	file_asterai_proto_rawDesc = nil
	file_asterai_proto_goTypes = nil
	file_asterai_proto_depIdxs = nil
}
